name: ffmpeg_cbs
description: "Private FFmpegKit wrapper plugin for Korea CBS applications. Provides HLS stream recording."
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ^3.0.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  rxdart: ^0.28.0

flutter:
  plugin:
    platforms:
      android:
        package: kr.co.cbs.ffmpeg
        pluginClass: FFMpegCBSPlugin
      ios:
        pluginClass: FFMpegCBSPlugin
      
      # 현 프로젝트에에 windows 통합하려 했으나, 앱프로젝트 빌드시
      # 플러그인 windows측 실행경로 "\windows\x64\plugins\ffmpeg_cbs\Debug\bin\ffmpeg.exe"
      # 를 못 찾고 대신 "\windows\x64\runner\Debug\bin\ffmpeg.exe"를 계속 찾는 상황.

      # windows:
      #   pluginClass: FfmpegCbsPluginCApi
    